name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Create secrets.auto.tfvars
      run: |
        sh -c "cat > secrets.auto.tfvars" << EOT
        nc_username="${{ secrets.NAMECHEAP_USERNAME }}"
        nc_api_user="${{ secrets.NAMECHEAP_API_USER }}"
        nc_token="${{ secrets.NAMECHEAP_TOKEN }}"
        nc_ip_address="84.209.40.117"
        EOT

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
